/**
 * Writes the curated catalogue (src/lib/catalog.ts) as an idempotent SQL seed
 * migration, so the database and the app share one source.
 * Run: bun scripts/export-catalog-sql.ts
 */
import { writeFileSync } from "node:fs";

import { GIFT_TEMPLATES } from "../src/lib/catalog";

const q = (value: string) => `'${value.replace(/'/g, "''")}'`;
const j = (value: unknown) => `${q(JSON.stringify(value))}::jsonb`;

const lines: string[] = [
  "-- Curated Fabrikat catalogue. Generated by scripts/export-catalog-sql.ts — do not edit by hand.",
  "",
];

GIFT_TEMPLATES.forEach((t, index) => {
  lines.push(
    `insert into public.gift_templates (id, name, tagline, description, price_chf, tone, sort_order) values (${q(t.id)}, ${j(t.name)}, ${j(t.tagline)}, ${j(t.description)}, ${t.price}, ${q(t.tone)}, ${index})`,
    "on conflict (id) do update set name = excluded.name, tagline = excluded.tagline, description = excluded.description, price_chf = excluded.price_chf, tone = excluded.tone, sort_order = excluded.sort_order;",
  );
  t.items.forEach((item, itemIndex) => {
    lines.push(
      `insert into public.template_items (id, template_id, kind, name, maker, engraving_surcharge_chf, engraving_max_length, preference, sort_order) values (${q(item.id)}, ${q(t.id)}, ${q(item.kind)}, ${j(item.name)}, ${q(item.maker)}, ${item.engravingSurcharge ?? "null"}, ${item.engravingMaxLength ?? "null"}, ${item.preference ? j(item.preference) : "null"}, ${itemIndex})`,
      "on conflict (id) do update set template_id = excluded.template_id, kind = excluded.kind, name = excluded.name, maker = excluded.maker, engraving_surcharge_chf = excluded.engraving_surcharge_chf, engraving_max_length = excluded.engraving_max_length, preference = excluded.preference, sort_order = excluded.sort_order;",
    );
  });
  lines.push("");
});

const target = "supabase/migrations/20260916200100_seed_catalogue.sql";
writeFileSync(target, lines.join("\n"));
console.log(`wrote ${target}`);
