/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuoteReviewRouteImport } from './routes/quote-review'
import { Route as RecipientsRouteImport } from './routes/recipients'
import { Route as TemplatesRouteImport } from './routes/templates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteReviewRoute = QuoteReviewRouteImport.update({
  id: '/quote-review',
  path: '/quote-review',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipientsRoute = RecipientsRouteImport.update({
  id: '/recipients',
  path: '/recipients',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quote-review': typeof QuoteReviewRoute
  '/recipients': typeof RecipientsRoute
  '/templates': typeof TemplatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quote-review': typeof QuoteReviewRoute
  '/recipients': typeof RecipientsRoute
  '/templates': typeof TemplatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quote-review': typeof QuoteReviewRoute
  '/recipients': typeof RecipientsRoute
  '/templates': typeof TemplatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/quote-review' | '/recipients' | '/templates'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/quote-review' | '/recipients' | '/templates'
  id: '__root__' | '/' | '/quote-review' | '/recipients' | '/templates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuoteReviewRoute: typeof QuoteReviewRoute
  RecipientsRoute: typeof RecipientsRoute
  TemplatesRoute: typeof TemplatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote-review': {
      id: '/quote-review'
      path: '/quote-review'
      fullPath: '/quote-review'
      preLoaderRoute: typeof QuoteReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipients': {
      id: '/recipients'
      path: '/recipients'
      fullPath: '/recipients'
      preLoaderRoute: typeof RecipientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuoteReviewRoute: QuoteReviewRoute,
  RecipientsRoute: RecipientsRoute,
  TemplatesRoute: TemplatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
